###Application
application:
###Common
common:
    swagger:
        title: Application API
        description: API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName: Jason
        contactUrl: 
        contactEmail: test@gmail.com
        license:
        licenseUrl:
        #defaultIncludePattern: /.*

### Spring Common
spring:
  profiles:
    active:
    - dev
    - mysql
    #- oracle
    - swagger

server:
  port: 8080

spring.datasource.hikari.connectionTimeout: 20000
spring.datasource.hikari.maximumPoolSize: 5
spring.datasource.hikari.poolName: HikariPoolZZZ

spring.security.user.name: admin
spring.security.user.password: admin123
spring.security.user.roles: ADMIN

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops','env','health','info','jhimetrics','logfile','loggers','prometheus','threaddump']
  endpoint:
    health:
      show-details: always #when-authorized
      roles: 'ROLE_ADMIN'
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      loggack: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true
         

spring.h2.console.enabled: false
      
logging:
  level:
    org.springframework: INFO
    com.zaxxer.hikari: DEBUG
    org.octopus: DEBUG
    root: ERROR  
    
spring.data.rest.base-path: /api
---
### Start
spring:
  profiles:
  - oracle
  jpa:
    show-sql: true
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: sql/oracle/import_app-oracle.sql,sql/oracle/import_component-oracle.sql
#select value from v$parameter where name='service_names' to get real service name to sort out ORA-12514, TNS issue
spring.datasource.url: jdbc:oracle:thin:@localhost:1521/ORCLCDB.localdomain
spring.datasource.username: oauth
spring.datasource.password: oauthpass
spring.datasource.driver-class-name: oracle.jdbc.OracleDriver
      
### End    
---
### Start
spring:
  profiles:
  - mysql
  jpa:
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: sql/import_app.sql,sql/import_component.sql,sql/import_user.sql

spring.datasource.url: jdbc:mysql://localhost:3306/rbacdb
spring.datasource.username: rbac
spring.datasource.password: rbac123
      
### End
--- 
### Start
spring:
  profiles:
  - h2
  jpa:
    show-sql: true
    database: H2
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: sql/import_app.sql,sql/import_component.sql
          
spring.datasource.url: jdbc:h2:mem:test
spring.h2.console.enabled: true
  
### End

--- 
### Start
spring:
  profiles:
  - test
  jpa:
    show-sql: true
    database: H2
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: sql/import_app.sql,sql/import_component.sql
          
spring.datasource.url: jdbc:h2:mem:test
spring.h2.console.enabled: true
  
### End